---
- name: SAVE RUNNING-CONFIG TO FILE
  hosts: CSR1KV-Pod1-3
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars: # for execution environment
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: DISPLAYING THE RUNNING-CONFIG
      ios_command:
        commands:
          - show running-config
      register: config
 
    - name: SAVE OUTPUT
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "show_run_65070171_{{ inventory_hostname }}.txt"
